Add homepage content
42eleven/kubecamp.io pull request #2
Opened 2023-05-20 19:31 UTC by koslib

2023-05-20 21:59 UTC, dreamPathsProjekt requested changes
Have some doubts about git tracking. Not content.

2023-05-20 21:59 UTC, dreamPathsProjekt commented on static/.DS_Store
Please remove and add to .gitignore

2023-05-20 21:59 UTC, dreamPathsProjekt commented on resources/_gen/assets/scss/css/base.scss_3b33337114e481782feeb60752452e17.json
Are these css fingerprinted files need to be git tracked? They always update fingerprints on any build (due to invalidate caching)

2023-05-20 23:41 UTC, koslib commented on static/.DS_Store
Apologies - fixed in 370cfab8fe1434c04878c8ddf2357c6279f54ffc

2023-05-20 23:43 UTC, koslib commented on resources/_gen/assets/scss/css/base.scss_3b33337114e481782feeb60752452e17.json
Agreed - handled in 49dff0e87616ad887c1eb6c69785d1f57cc3a518

2023-05-21 06:30 UTC, dreamPathsProjekt approved these changes

2023-05-21 06:30 UTC, merged